const $=id=>document.getElementById(id);
function notice(text){$('dialog-copy').textContent=text;$('message-dialog').showModal();}
document.querySelectorAll('[data-message]').forEach(button=>button.addEventListener('click',()=>notice(button.dataset.message)));
document.querySelectorAll('dialog .close,dialog [data-close]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
function previewVideoFiles(files){const feedback=$('file-feedback');if(!files.length)return;if(files.length!==1){feedback.textContent='Please choose one video at a time.';return;}const file=files[0];if(!/\.(mp4|mov)$/i.test(file.name)){feedback.textContent='Please choose an MP4 or MOV video.';return;}if(!file.size||file.size>500*1024*1024){feedback.textContent='Choose a video larger than 0 bytes and up to 500 MB.';return;}feedback.textContent=`${file.name} selected — ${(file.size/1048576).toFixed(1)} MB. Preview only; nothing uploaded.`;}
$('video-file')?.addEventListener('change',event=>previewVideoFiles(Array.from(event.target.files)));
const videoDropZone=$('video-drop-zone');
if(videoDropZone){let dragDepth=0;const fileDrag=event=>Array.from(event.dataTransfer?.types||[]).includes('Files');
videoDropZone.addEventListener('dragenter',event=>{if(!fileDrag(event))return;event.preventDefault();dragDepth++;videoDropZone.classList.add('drag-over');});
videoDropZone.addEventListener('dragover',event=>{if(!fileDrag(event))return;event.preventDefault();event.dataTransfer.dropEffect='copy';});
videoDropZone.addEventListener('dragleave',()=>{dragDepth=Math.max(0,dragDepth-1);if(!dragDepth)videoDropZone.classList.remove('drag-over');});
videoDropZone.addEventListener('drop',event=>{event.preventDefault();dragDepth=0;videoDropZone.classList.remove('drag-over');$('video-file').value='';previewVideoFiles(Array.from(event.dataTransfer?.files||[]));});
// Keep accidental file drops outside the target from navigating away from the dashboard.
window.addEventListener('dragover',event=>{if(fileDrag(event))event.preventDefault();});
window.addEventListener('drop',event=>{if(!fileDrag(event))return;event.preventDefault();dragDepth=0;videoDropZone.classList.remove('drag-over');if(!videoDropZone.contains(event.target))$('file-feedback').textContent='Drop your video inside the upload area, or use Choose file.';});
window.addEventListener('dragend',()=>{dragDepth=0;videoDropZone.classList.remove('drag-over');});}

document.querySelectorAll('[data-compose]').forEach(button=>button.addEventListener('click',()=>{$('compose-file').textContent=button.dataset.compose;$('post-title').value=button.dataset.compose.replace(/\.mp4$/,'').replace(/-/g,' ');$('compose-dialog').showModal();}));
const platformChoices=Array.from(document.querySelectorAll('[name=post-platform]'));
function selectedPlatforms(){return platformChoices.filter(input=>input.checked).map(input=>input.value);}
function syncDestinations(){const selected=selectedPlatforms();$('destination').value=selected.length===2?'all':(selected[0]||'');$('destination-summary').textContent=selected.length===2?'YouTube and X':(selected[0]||'Choose platforms');$('destination-all').checked=selected.length===platformChoices.length;$('destination-all').indeterminate=selected.length>0&&selected.length<platformChoices.length;$('youtube-fields').hidden=!selected.includes('YouTube');$('all-destinations').hidden=!selected.includes('X');$('destination-error').textContent='';syncSchedule();}
platformChoices.forEach(input=>input.addEventListener('change',syncDestinations));
$('destination-all')?.addEventListener('change',event=>{platformChoices.forEach(input=>input.checked=event.target.checked);syncDestinations();});
if(platformChoices.length)syncDestinations();
$('destination-picker')?.addEventListener('keydown',event=>{if(event.key==='Escape'&&event.currentTarget.open){event.preventDefault();event.stopPropagation();event.currentTarget.open=false;event.currentTarget.querySelector('summary').focus();}});
document.addEventListener('click',event=>{const picker=$('destination-picker');if(picker&&!picker.contains(event.target))picker.open=false;});
function syncSchedule(){const mode=document.querySelector('[name=timing]:checked')?.value;if(!mode)return;const selected=selectedPlatforms();$('schedule-field').hidden=mode!=='later';$('when').required=mode==='later';$('when').disabled=mode!=='later';$('platform-schedule').hidden=mode!=='separate';document.querySelectorAll('[data-schedule-platform]').forEach(row=>{const active=mode==='separate'&&selected.includes(row.dataset.schedulePlatform);row.hidden=!active;const input=row.querySelector('input');input.disabled=!active;input.required=active;});$('schedule-error').textContent='';}
document.querySelectorAll('[name=timing]').forEach(input=>input.addEventListener('change',syncSchedule));
$('compose-form')?.addEventListener('submit',event=>{event.preventDefault();const selected=selectedPlatforms();if(!selected.length){$('destination-error').textContent='Choose at least one platform.';$('destination-picker').open=true;$('destination-all').focus();return;}const mode=document.querySelector('[name=timing]:checked').value;const fields=mode==='later'?[$('when')]:mode==='separate'?Array.from(document.querySelectorAll('[data-schedule-platform] input')).filter(i=>!i.disabled):[];const past=fields.find(i=>!i.value||!Number.isFinite(new Date(i.value).getTime())||new Date(i.value).getTime()<=Date.now());if(past){$('schedule-error').textContent='Choose a future date and time for each scheduled post.';past.focus();return;}const formatted=i=>new Date(i.value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});const detail=mode==='now'?'Post ASAP for '+selected.join(' and '):mode==='later'?'Scheduled for '+selected.join(' and ')+' at '+formatted($('when')):selected.map(name=>name+' at '+formatted($(name==='YouTube'?'when-youtube':'when-x'))).join('; ');$('compose-dialog').close();notice(detail+'. Preview only — no video was uploaded, published or scheduled.');});
$('password-form')?.addEventListener('submit',event=>{event.preventDefault();if($('new-password').value!==$('confirm-password').value){$('password-error').textContent='Your new passwords do not match.';$('confirm-password').focus();return;}$('password-error').textContent='';event.target.reset();notice('Password form checked. No password was changed and no devices were signed out.');});
$('email-form')?.addEventListener('submit',event=>{event.preventDefault();$('pending-email').textContent=`In the app, the code would go to ${$('new-email').value}. Your current address would stay active until confirmed.`;$('email-form').hidden=true;$('email-confirmation').hidden=false;$('email-code').focus();});
function resetEmail(){$('email-form').reset();$('code-form').reset();$('code-error').textContent='';$('email-form').hidden=false;$('email-confirmation').hidden=true;}
$('cancel-email')?.addEventListener('click',()=>{resetEmail();$('new-email').focus();});
$('code-form')?.addEventListener('submit',event=>{event.preventDefault();if($('email-code').value!=='123456'){$('code-error').textContent='For this preview, enter 123456.';return;}resetEmail();notice('Email confirmation preview complete. Your real email address has not changed.');});
$('delete-form')?.addEventListener('submit',event=>{event.preventDefault();if(event.currentTarget.dataset.subscriptionStatus!=='ended'){notice('Account deletion is blocked while your subscription is active. Manage your subscription in Billing & Subscription, then wait until it has ended.');return;}event.target.reset();notice('This is the final account deletion step in the design preview. Nothing has been deleted and your real account is unchanged.');});

// Local design-preview preference, independent of the real signed-in account.
const backgroundKey='strider.preview.background.v1';
let backgroundDraft={image:'',fit:'cover',position:'center',fade:75},backgroundLoading=false,backgroundLoadId=0;
function validBackground(value){return value&&typeof value.image==='string'&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(value.image)&&['cover','contain','repeat'].includes(value.fit)&&['center','top','bottom'].includes(value.position)&&Number.isFinite(value.fade)&&value.fade>=20&&value.fade<=95;}
function paintBackground(element,value){if(!element)return;element.style.setProperty('--background-fade',value.fade/100);element.style.setProperty('--background-size',value.fit==='repeat'?'240px auto':value.fit);element.style.setProperty('--background-position',value.position);element.style.setProperty('--background-repeat',value.fit==='repeat'?'repeat':'no-repeat');if(element===document.body){element.classList.toggle('custom-background',Boolean(value.image));element.style.setProperty('--user-background',value.image?`url("${value.image}")`:'none');}else{element.style.backgroundImage=value.image?`url("${value.image}")`:'none';element.style.backgroundSize=value.fit==='repeat'?'120px auto':value.fit;element.style.backgroundPosition=value.position;element.style.backgroundRepeat=value.fit==='repeat'?'repeat':'no-repeat';}}
function renderBackgroundDraft(){paintBackground($('background-swatch'),backgroundDraft);if($('fade-value'))$('fade-value').textContent=backgroundDraft.fade+'%';}
try{const saved=JSON.parse(localStorage.getItem(backgroundKey)||'null');if(validBackground(saved))backgroundDraft=saved;}catch{if($('background-feedback'))$('background-feedback').textContent='Browser storage is unavailable. You can still preview a background.';}
if(document.body.classList.contains('dashboard-page'))paintBackground(document.body,backgroundDraft);
if($('background-form')){ $('background-fit').value=backgroundDraft.fit;$('background-position').value=backgroundDraft.position;$('background-fade').value=backgroundDraft.fade;renderBackgroundDraft(); }
for(const [id,key] of [['background-fit','fit'],['background-position','position'],['background-fade','fade']])$(id)?.addEventListener('input',event=>{backgroundDraft[key]=key==='fade'?Number(event.target.value):event.target.value;renderBackgroundDraft();$('background-feedback').textContent='Preview updated. Save to apply this to your dashboard.';});
$('background-file')?.addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;const requestId=++backgroundLoadId;backgroundLoading=false;const feedback=$('background-feedback');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){feedback.textContent='Please choose a JPG, PNG or WebP image up to 5 MB.';event.target.value='';return;}backgroundLoading=true;feedback.textContent='Preparing your image…';let url;try{url=URL.createObjectURL(file);const img=new Image();img.src=url;await img.decode();if(requestId!==backgroundLoadId)return;const scale=Math.min(1,1600/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const context=canvas.getContext('2d');context.drawImage(img,0,0,canvas.width,canvas.height);backgroundDraft.image=canvas.toDataURL('image/webp',.85);renderBackgroundDraft();feedback.textContent='Image ready. Save to use it on your dashboard.';}catch{if(requestId===backgroundLoadId)feedback.textContent='That image could not be opened. Please try another file.';}finally{if(url)URL.revokeObjectURL(url);if(requestId===backgroundLoadId)backgroundLoading=false;}});
$('background-form')?.addEventListener('submit',event=>{event.preventDefault();const feedback=$('background-feedback');if(backgroundLoading){feedback.textContent='Please wait until your image is ready.';return;}if(!backgroundDraft.image){feedback.textContent='Choose an image first, or use Reset to default.';return;}try{localStorage.setItem(backgroundKey,JSON.stringify(backgroundDraft));feedback.textContent='Background saved in this browser. Open your dashboard to see it.';}catch{feedback.textContent='Could not save: browser storage may be full or blocked. Try a smaller image or allow site storage.';}});
$('background-reset')?.addEventListener('click',()=>{try{localStorage.removeItem(backgroundKey);}catch{$('background-feedback').textContent='Could not clear browser storage. Please allow site storage and try again.';return;}backgroundLoadId++;backgroundLoading=false;backgroundDraft={image:'',fit:'cover',position:'center',fade:75};$('background-form').reset();renderBackgroundDraft();$('background-feedback').textContent='Default background restored.';});
