(()=>{'use strict';
const endpoint=document.body.dataset.statusEndpoint,byId=id=>document.getElementById(id);
const labels={resolved:'Resolved',operational:'Operational',checking:'Checking a possible issue',unknown:'Status unverified',degraded:'Service disruption',outage:'Outage reported',maintenance:'Maintenance',no_reported_incident:'No incident reported'};
const headlines={operational:'Monitored services are operational',unknown:'Some service checks are unavailable',degraded:'Some services need attention',outage:'A service outage has been reported',maintenance:'Maintenance is in progress'};
const icons={youtube:'youtube.com.png',facebook:'facebook.com.png',instagram:'instagram.com.png',tiktok:'tiktok-brand.png',x:'x-brand.png'};
let busy=false;let serviceNames={};
function phaseLabel(value){return value.charAt(0).toUpperCase()+value.slice(1);}
function node(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function date(text){const d=new Date(text);return Number.isFinite(d.getTime())?d.toLocaleString('en-GB',{timeZone:'UTC',dateStyle:'medium',timeStyle:'short'})+' UTC':'Time unavailable';}
function badge(state){return node('span',labels[state]||state,'badge '+(Object.hasOwn(labels,state)?state:'unknown'));}
function services(data){for(const [id,monitored] of [['status-services',true],['status-platforms',false]]){const root=byId(id);if(!root)continue;root.replaceChildren();for(const s of data.services.filter(s=>s.monitored===monitored)){const card=node('article',undefined,'service'),head=node('div',undefined,'service-heading'),title=node('h3',s.name);if(icons[s.id]){const icon=node('img');icon.src='platform-icons/'+icons[s.id];icon.alt='';title.prepend(icon);}head.append(title,badge(s.state));card.append(head,node('p',s.monitored?(s.checked_at?'Last check: '+date(s.checked_at)+(s.fresh?'':' · needs a fresh check'):'No check recorded yet'):'Reported incidents only'));root.append(card);}}}
function incidents(items,target,resolved){const root=byId(target);root.replaceChildren();if(!items.length){root.append(node('p',resolved?'No resolved incidents have been recorded yet.':'No active incidents are currently recorded. The Live status page shows current availability.','empty'));return;}for(const i of items){const card=node('article',undefined,'incident');card.id='incident-'+i.id;const contents=resolved?node('details'):card;if(resolved){contents.append(node('summary',i.title));card.append(contents);}else contents.append(node('h3',i.title));const meta=node('div',undefined,'incident-meta');meta.append(badge(resolved?'resolved':i.severity),node('span',phaseLabel(i.phase)),node('span',i.automatic?'Automatic check':'Strider update'),node('span',i.components.map(id=>serviceNames[id]||id).join(' · ')));contents.append(meta);const list=node('ol',undefined,'timeline');for(const u of i.updates){const item=node('li');item.append(node('strong',phaseLabel(u.phase)),node('p',u.message));const at=node('time',date(u.at));at.dateTime=u.at;item.append(at);list.append(item);}contents.append(list);root.append(card);}}
async function refresh(){if(busy)return;busy=true;byId('status-refresh').disabled=true;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const response=await fetch(endpoint,{cache:'no-store',credentials:'omit',signal:controller.signal});if(!response.ok)throw Error('feed unavailable');const data=await response.json();if(data.schema_version!==1||!Array.isArray(data.services)||!Array.isArray(data.incidents)||!Number.isFinite(Date.parse(data.generated_at))||Math.abs(Date.now()-Date.parse(data.generated_at))>240000)throw Error('invalid or stale feed');byId('status-headline').textContent=headlines[data.overall]||headlines.unknown;byId('status-indicator').className='dot '+(headlines[data.overall]?data.overall:'unknown');byId('status-detail').textContent='Live availability checks and published incident updates. This page refreshes every minute.';byId('status-updated').textContent='Feed updated '+date(data.generated_at)+'. All times shown in UTC.';serviceNames=Object.fromEntries(data.services.map(s=>[s.id,s.name]));services(data);incidents(data.incidents.filter(i=>i.phase!=='resolved'),'status-active',false);incidents(data.incidents.filter(i=>i.phase==='resolved'),'status-history',true);}catch(error){byId('status-headline').textContent='Live status cannot be verified';byId('status-indicator').className='dot unknown';byId('status-detail').textContent='The status feed could not be reached or is out of date. This may be a connection or service problem; it does not confirm that everything is working.';byId('status-updated').textContent='We’ll retry automatically. You can also press Refresh.';for(const id of ['status-services','status-platforms'])if(byId(id))byId(id).replaceChildren(node('p','Current checks unavailable.','empty'));for(const id of ['status-active','status-history'])byId(id).replaceChildren(node('p','Incident information is temporarily unavailable.','empty'));}finally{clearTimeout(timer);busy=false;byId('status-refresh').disabled=false;}}
byId('status-refresh').addEventListener('click',refresh);refresh();setInterval(refresh,60000);
})();
